# fly.toml app configuration file generated for pocketbase-still-forest-7557 on 2024-12-06T14:04:27-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pocker'
primary_region = 'fra'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source = "data"
  destination = "/data"
  initial_size = "1gb" 

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

  
