# fly.toml app configuration file generated for pocker-staging on 2024-12-26T05:01:11-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pocker-staging'
primary_region = 'sjc'
swap_size_mb = 512

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "data"
  destination = "/data"
  initial_size = "1gb" 

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1


  
